## PvP-Invite System by SlimeLab MC Server

    messages:
      # Placeholder %player%
      Need_Invite: "&6請先使用蹲下+左鍵發送對決邀請!"
      Wait_for_Accept: "&6已寄送邀請給 &b%player% &6正在等待他的回覆"
      Invite: "&b%player% &6邀請你進行決鬥"
      Accept: "&6你同意了 &b%player% &b的決鬥邀請"
      Deny: "&6你拒絕了 &b%player% &b的決鬥邀請"
      AcceptTo: "&b%player% &b同意了你的決鬥邀請"
      DenyTo: "&b%player% &b拒絕了你的決鬥邀請"
      ChooseAccept: "&a[同意]"
      ChooseDeny: "&c[拒絕]"
      ChooseCommand: "/pvp Accept ,/pvp Deny"
      PVPStart: "&6決鬥將在%time%秒後開始!!!"
      PVPEnd: "&6決鬥結束，獲勝者 &b%player%"
